---
language: node_js
node_js:
  - "4"
  - "node"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_script:
  - yarn global add bower phantomjs-prebuilt
  - bower install
